
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnujywpxufgaxgfxamxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudWp5d3B4dWZnYXhnZnhhbXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjMwOTYsImV4cCI6MjA2MTY5OTA5Nn0.mN7BP9TjUYyuuRXlLfBK62_iAfg0ODtFNGI9m5T-rxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Função para testar a conexão com o Supabase
export const testSupabaseConnection = async () => {
  try {
    const { error } = await supabase.from('colaboradores').select('count', { count: 'exact' }).limit(1);
    if (error) {
      console.error("Erro na conexão com o Supabase:", error);
      return false;
    }
    console.log("Conexão com o Supabase bem-sucedida");
    return true;
  } catch (err) {
    console.error("Erro ao verificar conexão com o Supabase:", err);
    return false;
  }
};
